spring:
  application:
    name: airport-distance-service

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:airportdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000        # 15 dəq
    refresh-token-expiration: 604800000    # 7 gün

airportgap:
  api:
    base-url: ${AIRPORTGAP_URL}

cors:
  allowed-origins: "http://localhost:5173"

logging:
  level:
    root: INFO
    com.airport.airportdistanceservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId:-no-trace}] %-5level %logger{36} - %msg%n"

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}

resilience4j:
  circuitbreaker:
    instances:
        airportGapApi:
            sliding-window-size: 10
            failure-rate-threshold: 50
            wait-duration-in-open-state: 30s
            permitted-number-of-calls-in-half-open-state: 3
            minimum-number-of-calls: 5
            slow-call-duration-threshold: 5s
            slow-call-rate-threshold: 80

  retry:
    instances:
        airportGapApi:
            max-attempts: 3
            wait-duration: 1s
            retry-exceptions:
              - org.springframework.web.reactive.function.client.WebClientException
              - com.airport.airportdistanceservice.exception.ExternalServiceException #AirportGapClient gelen 5xx xetalarini bu tipe cevirir deye
            ignore-exceptions:
              - com.airport.airportdistanceservice.exception.AirportNotFoundException

  ratelimiter:
    instances:
      distanceApi:
        limit-for-period: 5
        limit-refresh-period: 1m
        timeout-duration: 0

bucket4j:
  limit-per-minute: 3

