spring:
  application:
    name: airport-distance-service

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:airportdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000        # 15 dəq
    refresh-token-expiration: 604800000    # 7 gün

airportgap:
  api:
    base-url: ${AIRPORTGAP_URL}

cors:
  allowed-origins: "http://localhost:5173"

logging:
  level:
    root: INFO
    com.airport.airportdistanceservice: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId:-no-trace}] %-5level %logger{36} - %msg%n"

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
